#!/usr/bin/env bash

specs_root_path="./test"
specs_extension=".bats"

execute_spec() {
    local -r filename="${1:-}"
    bats -p $filename
}

spec_name() {
    local name="${1:-}"

    name=${name/$specs_root_path\//}
    name=${name/$specs_extension/}
    name=${name/__/::}

    echo $name
}

execute_specs() {
    local -r slug="${1:-}"

    while read -d '' filename; do

        if [[ -n $slug ]]; then
            if [[ $filename = ${filename/$slug/} ]]; then
                continue;
            fi
        fi

        printf "\\n[%s] executing <%s>...\\n" "${slug:-all}" "$(spec_name $filename)"
        execute_spec "${filename}"
    done < <(find $specs_root_path -name "*$specs_extension" -not -path "$specs_root_path/test_helper/*" -maxdepth 2000 -type f -print0)
}

execute_specs "$@"
