#!/bin/bash

[[ -f $PWD/.tdkrc ]] && source $PWD/.tdkrc
[[ -f $PWD/../.tdkrc ]] && source $PWD/../.tdkrc

include "microservices"

MICROSERVICE_NAME="infrastructure/config-server"
MICROSERVICE_PARAMETERS="--spring.zipkin.enabled=false \
--eureka.client.enabled=true \
--eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/ \
--spring.cloud.config.failFast=true \
--spring.profiles.active=dev,local \
--spring.cloud.config.server.git.uri=file:///home/jesus/development/tradis/infrastructure/config-repo"
JAVA_OPTS="-Xmx32m -XX:MaxMetaspaceSize=64M"

microservice_lifecycle "$MICROSERVICE_NAME" --parameters "$MICROSERVICE_PARAMETERS" "$@"
