#!/bin/bash

[[ -f $PWD/.tdkrc ]] && source $PWD/.tdkrc
[[ -f $PWD/../.tdkrc ]] && source $PWD/../.tdkrc

include "microservices"

MICROSERVICE_NAME="infrastructure/eureka"
MICROSERVICE_PARAMETERS="--spring.zipkin.enabled=false \
--server.port=8761 \
--spring.profiles.active=dev,local"
JAVA_OPTS="-Xmx64m -XX:MaxMetaspaceSize=100M"

microservice_lifecycle "$MICROSERVICE_NAME" --parameters "$MICROSERVICE_PARAMETERS" "$@"
