#!/bin/bash

[[ -f $PWD/.tdkrc ]] && source $PWD/.tdkrc
[[ -f $PWD/../.tdkrc ]] && source $PWD/../.tdkrc

include "microservices"

MICROSERVICE_NAME="business/registry-site"
MICROSERVICE_PARAMETERS="--spring.zipkin.enabled=false \
--spring.cloud.config.uri=http://localhost:8888/ \
--spring.profiles.active=dev,local \
--spring.cloud.config.label=borrar \
--spring.redis.sentinel.master=redis-cluster \
--spring.redis.sentinel.nodes=10.100.251.48:26379,10.100.251.49:26379"
JAVA_OPTS="-Xmx200m \
-XX:MaxMetaspaceSize=200M \
-Djavax.net.ssl.trustStore=/home/jesus/development/tradis/business/registry-site/src/main/resources/keystore/desa/almacen.ks \
-Dtruststore.path=/home/jesus/development/tradis/business/registry-site/src/main/resources/keystore/desa/almacen.ks \
-Djavax.net.ssl.trustStorePassword=edocalmacen \
-Dtruststore.pass=edocalmacen"

microservice_lifecycle "$MICROSERVICE_NAME" --parameters "$MICROSERVICE_PARAMETERS" "$@"

