#!/bin/bash

[[ -f $PWD/.tdkrc ]] && source $PWD/.tdkrc
[[ -f $PWD/../.tdkrc ]] && source $PWD/../.tdkrc

include "microservices"

MICROSERVICE_NAME="business/user-notificator"
MICROSERVICE_PARAMETERS="--spring.zipkin.enabled=false \
--spring.cloud.config.uri=http://localhost:8888/ \
--spring.cloud.config.label=develop \
--spring.profiles.active=dev,local \
--server.port=8082"
JAVA_OPTS="-Xmx100m -XX:MaxMetaspaceSize=100M"

microservice_lifecycle "$MICROSERVICE_NAME" --parameters "$MICROSERVICE_PARAMETERS" "$@"
